<?php
function munros_bagg_menu() {
  $items = array();
	$items['my-munros']	=	array(
    'title' => 'My Munros',
    'page callback' => 'munros_bagg_view_forward',
    'page arguments' => array(1),
    'access callback' => TRUE,

	);
  $items['my-munros/%munros_bagg_user'] = array(
    'title' => 'My Munros',
    'page callback' => 'munros_bagg_view_own',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'menu_name' => 'user-menu',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10
  );
  $items['my-munros/%munros_bagg_user/default'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Default primary tab',
    'weight' => 1,
  );
  $items["my-munros/%munros_bagg_user/edit"] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Edit',
		'page callback' => 'drupal_get_form',
    'page arguments' => array('munros_bagg_form'),
    'access callback' => TRUE,
    'file' => 'munros_bagg.page.inc',
    'weight' => 2,
  );
  $items['area-munros/%munros_bagg_node/%munros_bagg_user'] = array(
    'title' => 'My Area',
		'title callback' => 'munros_bagg_node_title',
		'title arguments' => array(1, 2),
    'page callback' => 'munros_bagg_view_another',
    'page arguments' => array(1, 2),
    'access callback' => 'munros_bagg_menu_access',
		'access arguments' => array(1, 2),
    'menu_name' => 'user-menu',
    'expanded' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10
  );
  return $items;
}
function munros_bagg_menu_access($node, $user) {
	return FALSE;
	return TRUE;
}
function munros_bagg_user_to_arg($arg) {
  global $user; return $user->uid;
}
function munros_bagg_user_load($uid=NULL) {
  if (!isset($uid)) { 
    $uid = $GLOBALS['user']->uid;
  } 
  return $uid; 
}   
function munros_bagg_node_title($node, $user) {
	if(arg(0)=='node') {
	$node = node_load($node);
		return $node->type . " Munros";
	}
}
function munros_bagg_node_to_arg($arg) {
	if(arg(0) == 'node' && is_numeric(arg(1))) {
		return arg(1);
	}
}
function munros_bagg_node_load($nid=NULL) {
	return $nid;
}   
function munros_bagg_view_another($uid) {
	return "TESTER";
}
function munros_bagg_view_forward() {
	global  $user;
	if(is_numeric($user->uid)) {
		drupal_goto("my-munros/" . $user->uid);
	}
}
function munros_bagg_view_own($uid) {
  return views_embed_view('munros_counters', 'page_1', $uid);
}   
function munros_bagg_view_page($user, $id) { 
  return "HERE PAGE";
}
function munros_bagg_date_popup_process_alter(&$element, &$form_state, $context) {
  unset($element['date']['#title']);
	$element['date']['#size'] = 8;
  unset($element['date']['#description']);
}
/**
 * Implementation of hook_theme().
 */
function munros_bagg_theme() {
  return array(
    'munros_fieldset' => array(
      'render element' => 'form',
      'file' => 'munros_bagg.theme.inc'
    ),
    'munros_bagg_munros' => array(
      'render element' => 'form',
      'file' => 'munros_bagg.theme.inc'
    ),
    'munros_bagg_table' => array(
      'render element' => 'form',
      'file' => 'munros_bagg.theme.inc',
    ),
    'munros_bagg_tabs' => array(
      'render element' => 'form',
      'file' => 'munros_bagg.theme.inc'
    )
  );
}
function munros_bagg_sort_by_order($a, $b) {
  if (is_array($a) && is_array($b) && isset($a['#area'], $b['#area'])) {
		$a = (int) $a['order']['#markup'];
		$b = (int) $b['order']['#markup'];
		return $a > $b;
  }
  return 0;
}
